name: Sync Yuque Blog

on:
  schedule:
    # 每天 UTC 时间 0 点运行 (北京时间 8 点)
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create env file
        run: |
          echo "YUQUE_USERNAME=${{ secrets.YUQUE_USERNAME }}" >> .elog.env
          echo "YUQUE_PASSWORD=${{ secrets.YUQUE_PASSWORD }}" >> .elog.env
          echo "YUQUE_LOGIN=${{ secrets.YUQUE_LOGIN }}" >> .elog.env
          echo "YUQUE_REPO=${{ secrets.YUQUE_REPO }}" >> .elog.env
          echo "R2_ACCESSKEYID=${{ secrets.R2_ACCESSKEYID }}" >> .elog.env
          echo "R2_SECRET_ACCESSKEY=${{ secrets.R2_SECRET_ACCESSKEY }}" >> .elog.env
          echo "R2_BUCKET=${{ secrets.R2_BUCKET }}" >> .elog.env
          echo "R2_ENDPOINT=${{ secrets.R2_ENDPOINT }}" >> .elog.env
          echo "R2_HOST=${{ secrets.R2_HOST }}" >> .elog.env
          echo "SILICON_FLOW_API_KEY=${{ secrets.SILICON_FLOW_API_KEY }}" >> .elog.env

      - name: Sync blog from Yuque
        run: npm run elog:sync

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code ./src/content/blog/ || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email '<>'
          git add .
          git commit -m "chore: sync blog from Yuque"
          git push